- name: First 5 minutes in new servers
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  vars_files:
    - ansible-vars.yml

  tasks:
    ## Step1/3: Making sure server has secure packages
    - name: Update APT packages cache
      apt: update_cache=yes

    - name: Perform aptitude safe-upgrade
      apt:
        upgrade: dist

    ## Step2/3: Making SSH secure
    - name: Disallow root SSH access
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify: Restart ssh

    - name: Disallow password authentication
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: Restart ssh

    - name: Change ssh port to 8888
      set_fact:
      ansible_port: 90

    ## Step3/3: Making network layer more secure
    - name: Install a list of packages
      apt:
        pkg:
          - python
          - ufw
          - fail2ban
          - unattended-upgrades
          - logwatch

    - name: Allow ssh and http(s) connections # VERIFY: > ufw status        > sudo netstat -ntlp | grep LISTEN
      ufw: rule=allow port={{ item }}
      with_items:
        - "{{ ufw_allowed_ports }}"

    - name: Enable ufw/firewall
      ufw: state=enabled policy=deny

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
