- name: First 5 minutes in new servers
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  vars_files:
    - ansible-vars.yml

  tasks:
    - name: Update APT packages cache
      apt: update_cache=yes

    - name: Perform aptitude safe-upgrade
      apt:
        upgrade: dist

    - name: Disallow root SSH access
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify: Restart ssh

    - name: Disallow password authentication
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: Restart ssh

    - name: Install required packages
      apt: state=installed pkg={{ item }}
      with_items:
        - "{{ required_packages }}"

    # Allow only ssh and http(s) ports
    - name: Allow ssh and http(s) connections
      ufw: rule=allow port={{ item }}
      with_items:
        - "{{ ufw_allowed_ports }}"

    - name: Enable ufw/firewall
      ufw: state=enabled policy=deny

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
