- name: First 5 minutes in new servers
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root

  tasks:
    ## Step1/3: Making sure server has secure packages
    - name: Update APT packages cache
      apt: update_cache=yes

    - name: Perform aptitude safe-upgrade
      apt:
        upgrade: dist

    ## Step2/3: Making SSH secure
    - name: Disallow root SSH access
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify: Restart ssh

    - name: Disallow password authentication
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: Restart ssh

    - name: Change ssh port to 8888
      set_fact:
        ansible_port: 90

    ## Step3/3: Making network layer more secure
    - name: Install a list of packages
      apt:
        pkg:
          - python
          - ufw
          - fail2ban
          - unattended-upgrades
          - logwatch

    # VERIFY: > ufw status        > sudo netstat -ntlp | grep LISTEN
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Allow all access to tcp port 443
      ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: Allow all access to tcp port 90
      ufw:
        rule: allow
        port: "90"
        proto: tcp

    - name: Enable ufw/firewall
      ufw: state=enabled policy=deny

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
