- name: Docker containers cannot create their own access
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root

  tasks:
    - name: Deploy Docker daemon.json. # Ref: Withiut this the ufw rules are not followed. https://stackoverflow.com/questions/30383845/what-is-the-best-practice-of-docker-ufw-under-ubuntu
      copy:
        src: docker-daemon.json
        dest: /etc/docker/daemon.json
