# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      DB_USER: root
      DB_PASS: rootpass
      DB_HOST: 127.0.0.1
      DB_DB: test
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]


    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: 'jaidurgama' # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: Connect Ubuntu MySQL (SUDO)
        run: mysql –host 127.0.0.1 --port 3306 -u root -p jaidurgama
      
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build client side
        run: |
          cd vue-client
          npm ci
          npm run build --if-present
          npx jest
        env:
          CI: true
